name: Build and Deploy to IBM Cloud

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh

      - name: Login to IBM Cloud
        run: |
          ibmcloud login \
            --apikey ${{ secrets.IBM_API_KEY }} \
            -r ${{ secrets.IBM_REGION }}

      - name: Login to Container Registry
        run: |
          ibmcloud cr login

      - name: Build Docker Image
        run: |
          docker build -t icr.io/${{ secrets.REGISTRY_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push Image
        run: |
          docker push icr.io/${{ secrets.REGISTRY_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest

      - name: Configure Kubernetes
        run: |
          ibmcloud ks cluster config \
            --cluster ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to Cluster
        run: |
          kubectl rollout restart deployment/${{ secrets.IMAGE_NAME }}
